config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deploy20161213</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<%= link_to('Home', root_path) %>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<%= link_to('Home', root_path) %>

app/views/static_pages/home.html.erb
<h1>Deploy 2016</h1>

<ul>
  <li><a href=<%= static_pages_contact_path %> >Contacto</a></li>
  <li><a href=<%= static_pages_about_path %> >About</a></li>
</ul>